// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using AegisQuiz.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AegisQuiz.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AegisQuizDbContext))]
    [Migration("20260704025931_MoveOptionsToQuestionBase")]
    partial class MoveOptionsToQuestionBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AegisQuiz.Domain.Entities.BankTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("AllowedTenantIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisibilityScope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PRIVATE");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("BankTopics");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicantIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CorrectItemCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("EarnedScore")
                        .HasColumnType("numeric");

                    b.Property<string>("EndReason")
                        .HasColumnType("text");

                    b.Property<Guid>("ExamContestId")
                        .HasColumnType("uuid");

                    b.Property<string>("FinalAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("NumberOfTabSwitches")
                        .HasColumnType("integer");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("SnapshotQuestionIds")
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("TimeStarted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TimeSubmitted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalItemCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("Status");

                    b.HasIndex("ApplicantId", "Status");

                    b.ToTable("ExamSessions");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearnerLeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarInitial")
                        .HasColumnType("text");

                    b.Property<double>("AverageScore")
                        .HasColumnType("double precision");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer");

                    b.Property<double>("TotalScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Period", "PeriodStart", "Rank");

                    b.HasIndex("UserId", "Period", "PeriodStart")
                        .IsUnique();

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("IconEmoji")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleReward")
                        .HasColumnType("text");

                    b.Property<string>("TriggerCondition")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LearningAchievements");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningPath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LearningPaths");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningPathProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CompletionPercent")
                        .HasColumnType("double precision");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<Guid>("LearningPathId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LearningPathId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "LearningPathId")
                        .IsUnique();

                    b.ToTable("LearningPathProgresses");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningPathStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LearningObjective")
                        .HasColumnType("text");

                    b.Property<Guid>("LearningPathId")
                        .HasColumnType("uuid");

                    b.Property<double>("PassScore")
                        .HasColumnType("double precision");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LearningPathId", "StepOrder");

                    b.ToTable("LearningPathSteps");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.Notebook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourcePdfUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notebooks");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.NotebookChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("GeneratedQuestionIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("KeyPointsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NotebookId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NotebookId");

                    b.ToTable("NotebookChapters");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountRequired")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionId");

                    b.HasIndex("PaymentCode")
                        .IsUnique();

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.PersonAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AchievementId");

                    b.ToTable("PersonAchievements");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.QuestionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttemptDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectedAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttemptDate");

                    b.HasIndex("UserId", "AttemptDate");

                    b.ToTable("QuestionAttempts");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.QuestionAttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttemptDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryCode")
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<double>("PointsEarned")
                        .HasColumnType("double precision");

                    b.Property<double>("PointsMax")
                        .HasColumnType("double precision");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubmittedAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TimeTakenSec")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.HasIndex("UserId");

                    b.HasIndex("AttemptId", "CategoryCode");

                    b.ToTable("QuestionAttemptAnswers");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.QuestionBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectOption")
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Options")
                        .HasColumnType("text[]");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode");

                    b.ToTable("Questions");

                    b.HasDiscriminator<string>("QuestionType").HasValue("QuestionBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.EssayQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.Property<string>("GradingRubric")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("ESSAY");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.FillBlankQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.HasDiscriminator().HasValue("FILL_BLANK");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.MatchingQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.HasDiscriminator().HasValue("MATCHING");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.MultiChoiceQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.HasDiscriminator().HasValue("MULTI");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.OrderingQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.HasDiscriminator().HasValue("ORDERING");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.ShortAnswerQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.HasDiscriminator().HasValue("SHORT_ANSWER");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.SingleChoiceQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.HasDiscriminator().HasValue("SINGLE");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.TrueFalseQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.HasDiscriminator().HasValue("TRUE_FALSE");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.BankTopic", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.BankTopic", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningPathProgress", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.LearningPath", "LearningPath")
                        .WithMany()
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningPath");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningPathStep", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.LearningPath", "LearningPath")
                        .WithMany("Steps")
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningPath");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.NotebookChapter", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.Notebook", "Notebook")
                        .WithMany("Chapters")
                        .HasForeignKey("NotebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notebook");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.PersonAchievement", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.LearningAchievement", "Achievement")
                        .WithMany("PersonAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.BankTopic", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningAchievement", b =>
                {
                    b.Navigation("PersonAchievements");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningPath", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.Notebook", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
