// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using AegisQuiz.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AegisQuiz.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AegisQuizDbContext))]
    [Migration("20260912112239_AddHierarchyAndDynamicDomains")]
    partial class AddHierarchyAndDynamicDomains
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AegisQuiz.Domain.Entities.BankTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("AllowedTenantIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("DepthLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("DomainCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MaterializedPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuestionCountCached")
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Urn")
                        .HasColumnType("text");

                    b.Property<string>("VisibilityScope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PRIVATE");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DomainCode");

                    b.HasIndex("MaterializedPath");

                    b.HasIndex("ParentId");

                    b.HasIndex("Scope");

                    b.HasIndex("TenantId");

                    b.ToTable("BankTopics");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.DynamicDomain", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("ColorBadge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemStandard")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentDomainCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Code");

                    b.HasIndex("IsSystemStandard");

                    b.HasIndex("ParentDomainCode");

                    b.HasIndex("TenantId");

                    b.ToTable("DynamicDomains");

                    b.HasData(
                        new
                        {
                            Code = "EDUCATION",
                            ColorBadge = "#2563eb",
                            CreatedAt = new DateTime(2026, 9, 12, 11, 22, 33, 215, DateTimeKind.Utc).AddTicks(7120),
                            Description = "Khảo thí đại học, phổ thông, học thuật tổng quát",
                            DisplayOrder = 1,
                            Icon = "GraduationCap",
                            IsActive = true,
                            IsSystemStandard = true,
                            Name = "Giáo dục & Học thuật"
                        },
                        new
                        {
                            Code = "BANKING",
                            ColorBadge = "#059669",
                            CreatedAt = new DateTime(2026, 9, 12, 11, 22, 33, 216, DateTimeKind.Utc).AddTicks(7615),
                            Description = "Nghiệp vụ tín dụng, thanh toán, ngân quỹ, quản trị rủi ro",
                            DisplayOrder = 2,
                            Icon = "Landmark",
                            IsActive = true,
                            IsSystemStandard = true,
                            Name = "Tài chính - Ngân hàng"
                        },
                        new
                        {
                            Code = "HEALTHCARE",
                            ColorBadge = "#dc2626",
                            CreatedAt = new DateTime(2026, 9, 12, 11, 22, 33, 216, DateTimeKind.Utc).AddTicks(7680),
                            Description = "Y học, dược lâm sàng, quy trình điều dưỡng, kiểm soát nhiễm khuẩn",
                            DisplayOrder = 3,
                            Icon = "HeartPulse",
                            IsActive = true,
                            IsSystemStandard = true,
                            Name = "Y tế - Sức khỏe"
                        },
                        new
                        {
                            Code = "HSE",
                            ColorBadge = "#d97706",
                            CreatedAt = new DateTime(2026, 9, 12, 11, 22, 33, 216, DateTimeKind.Utc).AddTicks(7687),
                            Description = "An toàn vệ sinh lao động, PCCC, quy chuẩn ISO 45001",
                            DisplayOrder = 4,
                            Icon = "HardHat",
                            IsActive = true,
                            IsSystemStandard = true,
                            Name = "An toàn - Môi trường LĐ"
                        },
                        new
                        {
                            Code = "GOV_DRIVING",
                            ColorBadge = "#7c3aed",
                            CreatedAt = new DateTime(2026, 9, 12, 11, 22, 33, 216, DateTimeKind.Utc).AddTicks(7690),
                            Description = "Bộ 600 câu GPLX Bộ GTVT, 60 câu điểm liệt, sa hình AI",
                            DisplayOrder = 5,
                            Icon = "Car",
                            IsActive = true,
                            IsSystemStandard = true,
                            Name = "Sát hạch Lái xe Quốc gia"
                        },
                        new
                        {
                            Code = "IT_SECURITY",
                            ColorBadge = "#0284c7",
                            CreatedAt = new DateTime(2026, 9, 12, 11, 22, 33, 216, DateTimeKind.Utc).AddTicks(7696),
                            Description = "Bảo mật an ninh mạng, kiến trúc hệ thống, chứng chỉ CISSP/CompTIA",
                            DisplayOrder = 6,
                            Icon = "ShieldCheck",
                            IsActive = true,
                            IsSystemStandard = true,
                            Name = "An toàn TT & CNTT"
                        },
                        new
                        {
                            Code = "GENERAL",
                            ColorBadge = "#4b5563",
                            CreatedAt = new DateTime(2026, 9, 12, 11, 22, 33, 216, DateTimeKind.Utc).AddTicks(7700),
                            Description = "Kiến thức đại cương, kỹ năng mềm, văn hóa doanh nghiệp",
                            DisplayOrder = 7,
                            Icon = "Layers",
                            IsActive = true,
                            IsSystemStandard = true,
                            Name = "Tổng hợp / Đại cương"
                        });
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicantIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CorrectItemCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("EarnedScore")
                        .HasColumnType("numeric");

                    b.Property<string>("EndReason")
                        .HasColumnType("text");

                    b.Property<Guid>("ExamContestId")
                        .HasColumnType("uuid");

                    b.Property<string>("FinalAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("NumberOfTabSwitches")
                        .HasColumnType("integer");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("SnapshotQuestionIds")
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("TimeStarted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TimeSubmitted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalItemCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("Status");

                    b.HasIndex("ApplicantId", "Status");

                    b.ToTable("ExamSessions");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearnerLeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarInitial")
                        .HasColumnType("text");

                    b.Property<double>("AverageScore")
                        .HasColumnType("double precision");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer");

                    b.Property<double>("TotalScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Period", "PeriodStart", "Rank");

                    b.HasIndex("UserId", "Period", "PeriodStart")
                        .IsUnique();

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("IconEmoji")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleReward")
                        .HasColumnType("text");

                    b.Property<string>("TriggerCondition")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LearningAchievements");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningPath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LearningPaths");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningPathProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CompletionPercent")
                        .HasColumnType("double precision");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<Guid>("LearningPathId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LearningPathId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "LearningPathId")
                        .IsUnique();

                    b.ToTable("LearningPathProgresses");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningPathStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LearningObjective")
                        .HasColumnType("text");

                    b.Property<Guid>("LearningPathId")
                        .HasColumnType("uuid");

                    b.Property<double>("PassScore")
                        .HasColumnType("double precision");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LearningPathId", "StepOrder");

                    b.ToTable("LearningPathSteps");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.Notebook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourcePdfUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notebooks");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.NotebookChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("GeneratedQuestionIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("KeyPointsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NotebookId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NotebookId");

                    b.ToTable("NotebookChapters");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.OrganizationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("HierarchyPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("OrganizationUnits");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountRequired")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionId");

                    b.HasIndex("PaymentCode")
                        .IsUnique();

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.PersonAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AchievementId");

                    b.ToTable("PersonAchievements");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.QuestionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttemptDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectedAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttemptDate");

                    b.HasIndex("UserId", "AttemptDate");

                    b.ToTable("QuestionAttempts");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.QuestionAttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiExplanation")
                        .HasColumnType("text");

                    b.Property<double?>("AiScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("AttemptDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryCode")
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<double>("PointsEarned")
                        .HasColumnType("double precision");

                    b.Property<double>("PointsMax")
                        .HasColumnType("double precision");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubmittedAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TimeTakenSec")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.HasIndex("UserId");

                    b.HasIndex("AttemptId", "CategoryCode");

                    b.ToTable("QuestionAttemptAnswers");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.QuestionBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("text");

                    b.Property<Guid?>("ContextId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("contextId");

                    b.Property<string>("CorrectOption")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("DomainCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("EDUCATION")
                        .HasJsonPropertyName("domainCode");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("isCritical");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("text");

                    b.PrimitiveCollection<List<string>>("Options")
                        .HasColumnType("text[]");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasJsonPropertyName("questionType");

                    b.Property<string>("SubCategory")
                        .HasColumnType("text")
                        .HasJsonPropertyName("subCategory");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasJsonPropertyName("tags");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode");

                    b.HasIndex("ContextId");

                    b.HasIndex("DomainCode");

                    b.ToTable("Questions");

                    b.HasDiscriminator<string>("QuestionType").HasValue("QuestionBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.QuestionContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("TenantId");

                    b.ToTable("QuestionContexts");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomDomain")
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureFlagsJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeycloakRealmId")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("text");

                    b.Property<int>("ScaleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.TenantCoordinatePreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoordinateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("DomainCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("PresetCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PresetLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SynonymsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "DomainCode", "CoordinateType");

                    b.ToTable("TenantCoordinatePresets");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.TenantDomainConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("DomainCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DomainCode");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "DomainCode")
                        .IsUnique();

                    b.ToTable("TenantDomainConfigs");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OrgUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrgUnitId");

                    b.HasIndex("Role");

                    b.HasIndex("TenantId", "OrgUnitId");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.EssayQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.Property<string>("GradingRubric")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("ESSAY");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.FillBlankQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.HasDiscriminator().HasValue("FILL_BLANK");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.MatchingQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.HasDiscriminator().HasValue("MATCHING");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.MultiChoiceQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.HasDiscriminator().HasValue("MULTI");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.OrderingQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.HasDiscriminator().HasValue("ORDERING");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.ShortAnswerQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.HasDiscriminator().HasValue("SHORT_ANSWER");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.SingleChoiceQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.HasDiscriminator().HasValue("SINGLE");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.TrueFalseQuestion", b =>
                {
                    b.HasBaseType("AegisQuiz.Domain.Entities.QuestionBase");

                    b.HasDiscriminator().HasValue("TRUE_FALSE");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.BankTopic", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.BankTopic", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.DynamicDomain", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.DynamicDomain", "ParentDomain")
                        .WithMany("SubDomains")
                        .HasForeignKey("ParentDomainCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentDomain");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningPathProgress", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.LearningPath", "LearningPath")
                        .WithMany()
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningPath");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningPathStep", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.LearningPath", "LearningPath")
                        .WithMany("Steps")
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningPath");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.NotebookChapter", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.Notebook", "Notebook")
                        .WithMany("Chapters")
                        .HasForeignKey("NotebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notebook");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.OrganizationUnit", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.OrganizationUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.PersonAchievement", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.LearningAchievement", "Achievement")
                        .WithMany("PersonAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.QuestionBase", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.QuestionContext", "Context")
                        .WithMany("Questions")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Context");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.TenantDomainConfig", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.DynamicDomain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("AegisQuiz.Domain.Entities.OrganizationUnit", "OrgUnit")
                        .WithMany()
                        .HasForeignKey("OrgUnitId");

                    b.Navigation("OrgUnit");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.BankTopic", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.DynamicDomain", b =>
                {
                    b.Navigation("SubDomains");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningAchievement", b =>
                {
                    b.Navigation("PersonAchievements");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.LearningPath", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.Notebook", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.OrganizationUnit", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("AegisQuiz.Domain.Entities.QuestionContext", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
